name: qdtoday
slug: qdtoday
version: "20250803"
image: ghcr.io/solarflows/qdtoday
description: "QD - HTTP请求定时任务自动执行框架 base on HAR Editor and Tornado Server"
url: https://github.com/qd-today/qd
init: false
codenotary: fireflows@cock.li
arch:
  - aarch64
  - amd64
webui: "[PROTO:http]://[HOST]:[PORT:8923]"
ports:
  8923/tcp: 8923
ports_description:
  8923/tcp: "QD Web UI port"
environment:
  TZ: "Asia/Shanghai"
map:
  - config:rw
  - ssl:ro
startup: application
boot: manual
ingress: true
ingress_port: 8923
