name: AList-TvBox
slug: alist-tvbox
version: "1.28.0-build.25"
image: ghcr.io/solarflows/alist-tvbox
description: "AList proxy server for TvBox, support playlist and search."
url: https://github.com/power721/alist-tvbox
init: false
arch:
  - aarch64
  - amd64
icon: mdi:television-box
webui: "[PROTO:http]://[HOST]:[PORT:4567]"
ports:
  4567/tcp: 4567
  80/tcp: 5344
ports_description:
  4567/tcp: "Manager Web UI port"
  80/tcp: "Alist Web UI port"
environment:
  no_proxy: "*.aliyundrive.com"
  ALIST_PORT: "5344"
  INSTALL: "xiaoya"
# 可选配置项：修改后保存并重启 addon 生效。
options:
  LOW_MEMORY: true
  ATV_DEBUG: false
schema:
  LOW_MEMORY: bool?
  ATV_DEBUG: bool?
map:
  - config:rw
startup: application
boot: manual
