name: Lucky(万吉)
slug: lucky
version: "2.27.2-build.10"
image: ghcr.io/solarflows/lucky
description: "替代socat,IPv6 tcp/udp 转发内网IPv4,动态域名服务"
url: https://github.com/gdy666/lucky
init: false
boot: manual
arch:
  - aarch64
  - amd64
ports:
  16601/tcp: 16601
ports_description:
  16601/tcp: "Lucky Web UI port"
ingress: true
ingress_port: 16601
icon: "mdi:server-network"
host_network: true
map:
  - config:rw
