---
name: 青龙面板 for HA
slug: qinglong
version: "2.21.0-build.8"
image: ghcr.io/solarflows/qinglong
description: "支持 Python3、JavaScript、Shell、Typescript 的定时任务管理平台"
url: https://github.com/whyour/qinglong
init: false
arch:
  - aarch64
  - amd64
webui: "http://[HOST]:[PORT:5700]/"
ports:
  5700/tcp: 5700
ports_description:
  5700/tcp: "Web UI port"
map:
  - config:rw
  - share:rw
startup: application
boot: manual
ingress: true
ingress_port: 5700
