---
name: FlareSolverr for HA
slug: flaresolverr
version: "3.5.0"
image: ghcr.io/solarflows/flaresolverr
description: "Bypass Cloudflare anti-bot page, support for Home Assistant."
url: https://github.com/FlareSolverr/FlareSolverr
init: false
codenotary: fireflows@cock.li
arch:
  - aarch64
  - amd64
ports:
  8191/tcp: 8191
  8192/tcp: 8192
ports_description:
  8191/tcp: "FlareSolverr proxy port"
  8192/tcp: "Prometheus exporter port"
environment:
  LOG_LEVEL: "info"
  TZ: "UTC"
cap_add:
  - SYS_ADMIN
  - IPC_LOCK
tmpfs:
  - /dev/shm:size=256M
map:
  - config:rw
startup: application
boot: manual
